#!/bin/sh

# User config
Work(){
    echo WORK!
}

Interval(){
    echo INTERVAL!
}

Finish(){
    echo FINISHED!
}
# -----------

POMODORO_STATE=$1

[ "$POMODORO_STATE" = "w" ] && Work
[ "$POMODORO_STATE" = "i" ] && Interval
[ "$POMODORO_STATE" = "f" ] && Finish
